### ISSUE TITLE
Website not loading, lost-redirect?

### ISSUE THREAD

**Issue by katerina7479** [thomasdavis/backbonetutorials#101]
I go to the website, and get a blank screen. On the console, there is an error:
Uncaught SyntaxError: Unexpected token < oldcp.dnsmadeeasy.com/lostredirect.html:1

**Comment by iannuttall** [comment]
I get:

Uncaught SyntaxError: Unexpected token < cdn.peercdn.com/instant.js:1

**Comment by urfolomeus** [comment]
+1

I had a quick look to see if I could just fix this myself but it looks like the peercdn url is invalid.

In the meantime you can always use http://cssor.com/wp-content/uploads/2012/10/Backbone-Tutorials.pdf :)
