### ISSUE TITLE
how to use a jQuery plugin?

### ISSUE THREAD

**Issue by exoer** [thomasdavis/backbonetutorials#16]
How to add a dependency for a jQuery plugin (e.g. jQuery.tmpl) to a backbone view?

**Comment by thomasdavis** [comment]
Great question, it's not easy.   I will cover this in depth on the weekend!

**Comment by exoer** [comment]
Great. Looking forward to it!

**Comment by andriijas** [comment]
Yeah or like handlebars + data bindings with models/collections.

**Comment by thomasdavis** [comment]
Is the plugin AMD compatible?

Yes? The plugin definition should then use $ from what ever jQuery module was depended ondefine([‘jquery’], function($){ $.fn.extend = myplugin; });

No? Are you able to edit the source code in your environment?

Yes -Wrap the original source in a define statement, pull in jQuery as a dependency such that the plugin is now AMD compatible

No - Simply use the order! plugin for jQuery and the plugins
