### ISSUE TITLE
it seems jQuery is now AMD compatible

### ISSUE THREAD

**Issue by lobo-tuerto** [thomasdavis/backbonetutorials#21]
Hello Thomas,

I was taking a look at the source of jQuery 1.7 and saw that it includes code to handle the AMD specification stuff. How would the application be modified to cope with this change now?

**Comment by thomasdavis** [comment]
You are exactly right.

jQuery and Underscore are both now AMD compatible, which means you can now load them asynchronously without the wrappers that the tutorial has.

I will update it soon or if you would like as a learning exercise you can attempt to fix the tutorial.

It's great news actually and hopefully Backbone.js will include the AMD support.

Though the author of Underscore.js is regretting including AMD and there is a small debate going on here(http://tagneto.blogspot.com/2011/11/why-not-amd.html).

With underscore and backbone AMD compatible the tutorial main.js will be much simpler.

**Comment by lobo-tuerto** [comment]
Well, it sounds like fun, I'm just starting with modular approaches and the learning exercise is welcomed. ;)

**Comment by kubetz** [comment]
Just FYI there a is a [pull request](https://github.com/thomasdavis/backbonetutorials/pull/25) with all libraries supporting AMD  :).
