### ISSUE TITLE
For each request all scripts are loaded

### ISSUE THREAD

**Issue by inigosola** [thomasdavis/backbonetutorials#24]
In the example (https://github.com/thomasdavis/backbonetutorials/tree/gh-pages/examples/modular-backbone) are two models (so two collections, two list views, and so on): user and project. For each request all script are loaded, users script and projects scripts. Is there any way to just load the users scripts hen the request is for user listing? Thank you.

**Comment by thomasdavis** [comment]
Yes so instead of in router.js requested the views and collections as dependencies instead move them to the correct route definition function and use require instead.

```
showUsers: function(){
  userListView.render();
},
```

now becomes

```
showUsers: function(){
  require(['views/user/list'], function(userListView){
```

userListView.render();
});
    },
