### ISSUE TITLE
Links - External Tutorials

### ISSUE THREAD

**Issue by kubetz** [thomasdavis/backbonetutorials#26]
What do you think about adding more external links to Backbone tutorials?
- Derick Bailey is maintaning list of [Backbone Resources](http://backbonetraining.net/resources) which contain a lot of links.
- [List on Backbone Wiki](https://github.com/documentcloud/backbone/wiki/Tutorials%2C-blog-posts-and-example-sites)
- [Backbone Patterns](http://ricostacruz.com/backbone-patterns/)

**Comment by thomasdavis** [comment]
They are pretty good resources, might just add them to the home page for now, is there a pull request?

**Comment by kubetz** [comment]
Now there is a [pull request](https://github.com/thomasdavis/backbonetutorials/pull/27) for it :).
