### ISSUE TITLE
backbone.js model backing DataTables grid?

### ISSUE THREAD

**Issue by erikcw** [thomasdavis/backbonetutorials#29]
It would be great to see an example of backbone.js providing the data for DataTables.

**Comment by thomasdavis** [comment]
Not sure I will have the time to get around to this to question, unless
there are a few more people wanting to know.

On Sat, Dec 10, 2011 at 11:20 AM, erikcw <
reply@reply.github.com

**Comment by victorhooi** [comment]
heya,

I'd like to throw my vote behind this as well - datatables (whether DataTable specifically, or another implementation - e.g. YUI) are one area that I think all the JS/Ajax magic has real wins in usability for the end-user.

I'd love to see an example with BackboneJS, and some grid widget of some kind.

Cheers,
Victor

**Comment by mygol** [comment]
+1

**Comment by benmxs** [comment]
big time interest!

**Comment by cmadsen** [comment]
+1

**Comment by thomasdavis** [comment]
oh god I thought I would never have to venture into the depths of datatables ever again

**Comment by victorhooi** [comment]
heya,

Lol, do you mean the JQuery Datatables plugin (http://datatables.net/), or just grid/datatable widgets in general?

YUI is currently revamping their Datatables implementation:

https://gist.github.com/1356355

And KnockoutJS has some pretty good grid examples here:

http://knockoutjs.com/examples/grid.html
http://knockoutjs.com/examples/gridEditor.html

Cheers,
Victor

**Comment by thomasdavis** [comment]
Ahh I see I thought the original question was originally for DataTables the jQuery widget, but it makes sense to offer an abstract solution that handles many use cases.

**Comment by victorhooi** [comment]
heya,

Yeah, a "this is how you should do grids properly " example in BacbkoneJS would be great =).

And I think it's fairly clear from the above comments that there's a real need for this.

Not sure what you'd use for the backend though - Django? _grins_.

Cheers,
Victor

**Comment by thomasdavis** [comment]
lol I always leave the backend agnostic in my examples, the only thing I'm concerned with is the dataType, xml or json. Because backbone only really works with json the example will be using json

**Comment by thomasdavis** [comment]
Attempting this weekend!

**Comment by victorhooi** [comment]
heya,

Any word? =).

Cheers,
Victor

**Comment by maralcbr** [comment]
+1

**Comment by Matt-Deacalion** [comment]
+1

**Comment by dhollenbeck** [comment]
+1

**Comment by bhang** [comment]
+1

**Comment by m0rganic** [comment]
+1

**Comment by bdetchison** [comment]
+1

**Comment by mlegenhausen** [comment]
+1

**Comment by pmgmendes** [comment]
+1

**Comment by dfried** [comment]
+1

**Comment by kchang808** [comment]
+1

**Comment by yanneves** [comment]
+1

**Comment by nguyenchiencong** [comment]
+1

**Comment by celmaun** [comment]
+∞

**Comment by thomasdavis** [comment]
Never really got to this, I implement DataTables with Backbone.js by simply rendering the html and then calling the html.
Such as on http://cdnjs.com
