### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by andrewdeandrade** [thomasdavis/backbonetutorials#31]
While I'm almost sure it's a permissive license like MIT or GPL, what is the license on this? Over on the require.js-rails gem, we want to set up some automated testing and forking your code would save some time in getting the test environment set up.

**Comment by thomasdavis** [comment]
Free to use in anyway what so ever, do you need a license put in the repo?

**Comment by andrewdeandrade** [comment]
No need, but it's your call. I just wanted to ask to make sure.

**Comment by thomasdavis** [comment]
Hey man, could you explain to a rails noob like me what this gem means for development.  I'm doing a full example app of backbone this weekend and wanting to as many concepts as possible.

**Comment by andrewdeandrade** [comment]
What is the use of Require.js you mean?

AMD, which is what the Dojo framework uses, basically allows you to develop you site as modules that can be asynchronously loaded. 

Check out this document on the Require.js site explaining the value of Asynchronous Module Definition:
http://requirejs.org/docs/whyamd.html

Addy Osmani just published a text on using Backbone.js with AMD:
https://github.com/addyosmani/backbone-fundamentals

The only problem with this gem at the moment is that Jasmine BDD tests don't yet work with them, but John Whitley, the dev behind this gem will be working on this over the next week or two, so I reckon it should be supported by the New Year.

**Comment by thomasdavis** [comment]
ahh wrong question, lol addy osmanis article is based off my demo that I done for him
https://github.com/thomasdavis/backbonetutorials/tree/gh-pages/examples/todo-app

I mean what does the require.js rails gem do? Does it allow you to use r.js as a gem?

**Comment by andrewdeandrade** [comment]
Yeah, r.js integration into sprockets is in the newest version (v0.5.1). With it, you put your build file in the config/ directory as a yml file instead of a build file in the folder above your app as a javascript file.

I'm not sure if r.js support is 100% complete yet since I've only played around with it in development. I haven't pushed to production with it yet.
