### ISSUE TITLE
Include link to a Backbone-relational tutorial?

### ISSUE THREAD

**Issue by PaulUithol** [thomasdavis/backbonetutorials#38]
I think it would make a great addition to include a link to http://antoviaque.org/docs/tutorials/backbone-relational-tutorial/ ? As far as I can tell, [Backbone-relational](https://github.com/PaulUithol/Backbone-relational/) is one of the most used Backbone extensions. I've had quite some requests for a tutorial, and this seems to be a very good one.

**Comment by thomasdavis** [comment]
Link added, sorry I get so busy!
