### ISSUE TITLE
Not returning 'new projectsModel'

### ISSUE THREAD

**Issue by j-5-s** [thomasdavis/backbonetutorials#40]
I see that every view/collection in the modular-backbone example is returning new instances of the Backbone objects except for the [projectsModel](https://github.com/thomasdavis/backbonetutorials/blob/gh-pages/examples/modular-backbone/js/models/projects.js). Can you please explain the reasoning behind this?

**Comment by thomasdavis** [comment]
This is in correct and it shouldn't return a new instance.   Slowly fixing up all the places that it does that
