### ISSUE TITLE
modular backbone example broken

### ISSUE THREAD

**Issue by norrs** [thomasdavis/backbonetutorials#42]
Current deployment of modular backbone example is broken.

See http://backbonetutorials.com/examples/modular-backbone

<code>
Uncaught TypeError: undefined is not a function main.js:9
Uncaught TypeError: undefined is not a function list.js:12
Uncaught TypeError: undefined is not a function list.js:9
Uncaught Error: Load timeout for modules: text!templates/home/main.html text!templates/users/list.html 
http://requirejs.org/docs/errors.html#timeout require.js:7
</code>

**Comment by egoens** [comment]
I'm receiving this same error as well.

**Comment by rashko** [comment]
to fix it - on js/libs/jquery/jquery.js change line 2 to: return Loader.$;

**Comment by peb7268** [comment]
I noticed that you dont have to load all the modules for backbone and underscore and jquery on every page. Something about their AMD complient"ness". They seem to conflict with each other. Instead load all your deps in the app.js file and access them from the global namespace. 

That worked for me anyway.
