### ISSUE TITLE
typo in a view example

### ISSUE THREAD

**Issue by Psycojoker** [thomasdavis/backbonetutorials#43]
Ohai,

Here in "Loading a template" http://backbonetutorials.com/what-is-a-view/ in the code example in the render function, "this.el.html" should be "this.$el.html" to refer to the jquery element.

I would have sended a pull request but I don't know how you generate your html and there is no instructions about that in the README.

Have a nice day,

**Comment by thomasdavis** [comment]
Fixed this up, sorry for the delay. Thanks!

**Comment by Psycojoker** [comment]
Great :) I'm closing the issue then.
