### ISSUE TITLE
Cross-domain example additional routes/pages

### ISSUE THREAD

**Issue by dkleehammer** [thomasdavis/backbonetutorials#46]
It would be beneficial for me and hopefully others to see how to add additional pages that are handled by the router.  Also, from the looks of the design, it appears that each page must have a login/logout function property for this to be handled correctly.  Am I correct?

I was following your example (which is very good, btw), but when I got to actually starting to build with this same type of layout, I ran into the routing problem.  If each page must have a login/logout function with this layout, is it possible to have the router check the session and display a different route (view) if they are not logged in?  This would make each page (view) much smaller and a single call to these views (login/logout)

I apologize if I missed something.

Thank you,

Daniel Kleehammer

**Comment by thomasdavis** [comment]
Hi Daniel, 
sorry for the late reply.

My tutorial wasn't really meant to imply any standard but only a demonstration of how you could listen to changes in the Session model by using

``` js
session.on('change:auth', function (model) {
  if(model.get('auth')){
    // render an authenticated view
  } else {
    // render a non-authenticated view
  }
});

When ever session auth changes any views bound to the session model can react accordingly. They do not necessarily have to be bound to the session model and might always render the same thing.

Does this help?
```

**Comment by dkleehammer** [comment]
Thomas,

I was hoping to not have views bound to the session model and actually tie session change to something else (maybe the router?).

This way it's not the view that is rendered differently, but the hash is actually changed to #/login.  This would change the views to be as clean as possible.  It would also allow me to put an interval checking if the session is timed out every x mins.

One of the main reasons for this is I'm using the app view as my main layout as it renders the header and user sidebar (using twitter bootstrap btw), but I need a different master layout for my login bar (header doesn't need settings/logout menu and no sidebar).

Have any ideas on how to handle this?  I like the layout and the control, just would like to move the session binding somewhere else to call Router.navigate('#/login') if need be.
