### ISSUE TITLE
modular-backbone-updated gives  an XMLHttpRequest error

### ISSUE THREAD

**Issue by SpencerCooley** [thomasdavis/backbonetutorials#47]
I have not played around with any of the code yet. I just opened up index.html in my browser and noticed the loading text never goes away. Looked at the console and saw this: 

XMLHttpRequest cannot load file:///home/spencer/Desktop/backbonetutorials/examples/modular-backbone-updated/templates/home/main.html. Cross origin requests are only supported for HTTP.

and

Uncaught Error: NETWORK_ERR: XMLHttpRequest Exception 101      line7 of text.js

**Comment by thomasdavis** [comment]
Hey @SpencerCooley , this error would have occured because there are different security restrictions at play when loading from file://, the example should be served from a webserver such that you can access it at http://
