### ISSUE TITLE
build.sh throws an error

### ISSUE THREAD

**Issue by TheWorkFarm** [thomasdavis/backbonetutorials#49]
This is my first time looking at require.js optimizer, but running ./build.sh I am getting 

`sed: 1: "output/index.html": invalid command code o`

regardless of the example I try. 

Seemingly the build completes and I can run the app, but "invalid command" always makes me itchy. 

Any ideas?

**Comment by thomasdavis** [comment]
Hey is this for backboneboilerplate or backbonetutorials?

**Comment by TheWorkFarm** [comment]
Holy crap that's embarrassing - can we delete rather than close?

**Comment by thomasdavis** [comment]
couldn't figure out how to delete sorry lol
