### ISSUE TITLE
Please remove references to "delete" of "var"s in examples

### ISSUE THREAD

**Issue by eranation** [thomasdavis/backbonetutorials#50]
first, thank you for providing this great tutorial...

one small issue I found (and others on the comments) - I think some of the code example might lead people to think that the delete keyword can be used for deleting variables. but this is not the case (please see this article for explanation:  http://perfectionkills.com/understanding-delete/)
to keep this a great tutorial, I would remove places where delete doesn't make sense.
if you use it for firebug cleanliness or other reason, I would explain so users won't be confused, and provide a link to the above article.

thanks again for a wonderful tutorial!

**Comment by thomasdavis** [comment]
removed them in latest commit, not really sure what i ever put them in lol -.-

thanks!
Thomas
