### ISSUE TITLE
difference between the backbone modular tutorials

### ISSUE THREAD

**Issue by headwinds** [thomasdavis/backbonetutorials#58]
I've tried out both examples and I like different things about each one.

To me, the routes.js file is the big key stone to these tutorials. 

In the original, I like how the instances of the views are created but don't like how the require works...

---

define([
  'jquery',
  'underscore',
  'backbone'
], function($, _, Backbone ){

```
app_router.on('route:showProjects', function(){
  require(['views/projects/list'], function(ProjectListView) {
    // Call render on the module we loaded in via the dependency array
    // 'views/projects/list'
    var projectListView = new ProjectListView();
    projectListView.render();
  })
});
```

---

but in the updated routes.js example -- although much less code, I don't like how the view looks like a singleton - I can't see how it's created except that I see it being passed in through the define  

---

define([
  'jquery',
  'underscore',
  'backbone',
  'views/home/main',
  'views/projects/list',
  'views/users/list'
## ], function($, _, Backbone, mainHomeView, projectListView, userListView )

showProjects: function(){
      // Call render on the module we loaded in via the dependency array
      // 'views/projects/list'
      projectListView.render();
    },

Can you comment here on this approach vs the original where you use var projectListView = new ProjectListView();

In the updated tutorial, I see that you've created amdjs version of backbone which seems like a significant move and you've explained this in your tutorial. 

backbone: 'libs/backbone/backbone-optamd3-min',

My issue is why do you have 2 tutorials? looking at Git commits - I see that they were both updated 20 days ago - with no read me files, I can't tell which one to use - I mean I imagine you believe the update tutorial is the better one... right?

**Comment by thomasdavis** [comment]
Sorry about that, I've removed the "updated" one.

So it's hard to actually choose a style, mostly everyone prefers different things.

You were right the "updated" example folder was old, singleton views were bad and a few other things.

You don't have to use inline require statements if you don't like, they are pretty verbose.   Throw them at the top with the rest of their dependencies.   

There are many different ways of loading non-AMD libraries, use.js is probably the most robust way.   I prefer to move quickly and find that the AMD augmented branches of backbone and underscore are faster to implement.

**Comment by headwinds** [comment]
when I google "backbone requirejs" your tutorial pops up first - it's probably the most important glue tutorial I've read this year! So thanks for clarifying - having the repo lineup with the article is a good move.

singleton views aren't so bad the way you were using them -- 1 main view or 1 projects view makes sense -- I just didn't know how then to create sub nested views for the individual projects. As I mentioned, I like seeing how each of the instances are created.

"You don't have to use inline require statements if you don't like, they are pretty verbose. Throw them at the top with the rest of their dependencies" 

That's cool - I was wondering about that - I like that approach as well as your use of "AMD augmented branches" to get up and running quickly -- hopefully popular code bases like Backbone will simply start adopting the requirejs pattern - it already seems like a natural candidate with it's underscore dependency.

**Comment by thomasdavis** [comment]
No worries, feel free to ask more questions or post suggestions even.
